services:
  app:
    build:
      context: .
    image: repaire-chevreuils-backend-image:1.0
    container_name: repaire-chevreuils-backend
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8080:8080"

  postgres-db:
    image: postgres
    container_name: repaire-chevreuils-db
    environment:
      POSTGRES_DB: "repaire-chevreuils-db"
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
